---
title: "fun_kontaktu_sumai"
author: "Ema Malinauskaite"
date: "2/12/2020"
output: html_document
---

```{r include=FALSE}
library("tidyverse")
library("data.table")
library("compareDF")
library("tidyr")
library("matlib")
```

V6 ir V13 - aminorugsciu tipai
V7 ir V14 - atomo tipai
V15 - kontakto plotas

# Grupavimo funkcija
```{r} 
fun_atom_kontaktu_grupavimui <- function(liz_kont) {#, nul_lentele_plat) { #pirmas - kontaktu lentele, antras - nuline lentele

liz_kont <- liz_kont %>%
  select(V6, V7, V13, V14, V15) %>% 
  mutate(V6 = recode_factor(V6,"MSE" = "MET")) %>% 
  mutate(V13 = recode_factor(V13,"MSE" = "MET"))
  
liz_kont$ar1_atom1 <- with(liz_kont, paste0(V6,V7))
liz_kont$ar2_atom2 <- with(liz_kont, paste0(V13,V14))

# liz_kont <- liz_kont %>% 
#   mutate(ar2_atom2 = recode_factor(ar2_atom2,".-." = "solvent"))

liz_kont_matrica <- as.matrix(data.frame(ar1_atom1 = liz_kont$ar1_atom1, ar2_atom2 = liz_kont$ar2_atom2))

surusiuoti_pavad <- liz_kont_matrica %>%
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame

kont_sumos <- cbind(liz_kont, surusiuoti_pavad) %>%
  rename(kontakto_tipas = ".")

kont_sumos <- kont_sumos %>% 
  group_by(kontakto_tipas) %>%
  summarise(kontakto_suma = sum(V15))
}
```
## Bandymas 
Duomenu ikelimas:
```{r}
lizocimo_kontaktai_1L63 <- data.table::fread("./lizocimai/1L63.contacts.interatom.table")
# <- readr::read_rds("./data/nuline_lentele_platusis.rds")
```

Skaiciavimai:
```{r}
paruosta_lentele_1L63 <- fun_atom_kontaktu_grupavimui(lizocimo_kontaktai_1L63)
paruosta_lentele_1L63
```

## Atomu tipu skaiciavimas
```{r}
pdb_sarasas <- readr::read_rds("./data/pro_344_sm_suppinfo.rds") %>%
  select(pdb) %>%
  drop_na()
```

1 ar
```{r}
suskaiciuoti_atomu_tipai_visiems_baltymams <- NULL
for (i in pdb_sarasas$pdb) {
lizocimo_kontaktai <- data.table::fread(paste("./lizocimai/",i,".contacts.interatom.table", sep = ""))
atomu_tipu_skaicius <- lizocimo_kontaktai %>% 
  select(V7, V15) %>% 
  group_by(V7) %>% 
  summarise(suma = sum(V15)) %>% 
  count()

suskaiciuoti_atomu_tipai_visiems_baltymams <- rbind(suskaiciuoti_atomu_tipai_visiems_baltymams, atomu_tipu_skaicius)
lizocimo_kontaktai = NULL
}
```

```{r}
suskaiciuoti_atomu_tipai_visiems_baltymams %>% summary()
```

2 ar:
```{r}
suskaiciuoti_atomu_tipai_visiems_baltymams2 <- NULL
for (i in pdb_sarasas$pdb) {
lizocimo_kontaktai <- data.table::fread(paste("./lizocimai/",i,".contacts.interatom.table", sep = ""))
atomu_tipu_skaicius <- lizocimo_kontaktai %>% 
  select(V14, V15) %>% 
  group_by(V14) %>% 
  summarise(suma = sum(V15)) %>% 
  count()

suskaiciuoti_atomu_tipai_visiems_baltymams2 <- rbind(suskaiciuoti_atomu_tipai_visiems_baltymams2, atomu_tipu_skaicius)
lizocimo_kontaktai = NULL
}
```

```{r}
suskaiciuoti_atomu_tipai_visiems_baltymams2 %>% summary()
```

pagal viska:
```{r}
suskaiciuoti_kontaktu_tipai_visiems_baltymams <- NULL
for (i in pdb_sarasas$pdb) {
lizocimo_kontaktai <- data.table::fread(paste("./lizocimai/",i,".contacts.interatom.table", sep = ""))
kontaktu_tipu_skaicius <- fun_atom_kontaktu_grupavimui(lizocimo_kontaktai) 

suskaiciuoti_kontaktu_tipai_visiems_baltymams <- rbind(suskaiciuoti_kontaktu_tipai_visiems_baltymams, nrow(kontaktu_tipu_skaicius))
lizocimo_kontaktai = NULL
}
suskaiciuoti_kontaktu_tipai_visiems_baltymams
```

```{r}
summary(suskaiciuoti_kontaktu_tipai_visiems_baltymams)
```
