---
title: "fun_kontaktu_sumai"
author: "Ema Malinauskaite"
date: "2/12/2020"
output: html_document
---

```{r include=FALSE}
library("tidyverse")
library("data.table")
library("compareDF")
library("tidyr")
library("matlib")
```

# fun_kontaktu_sumai

```{r}
fun_kontaktu_sumai <- function(liz_kont, nul_lentele_plat) { #pirmas - kontaktu lentele, antras - nuline lentele

liz_kont <- liz_kont %>%
  mutate(V6 = recode_factor(V6,"MSE" = "MET")) %>% 
  mutate(V13 = recode_factor(V13,"MSE" = "MET"))

liz_kont_matrica <- as.matrix(data.frame(ar_1 = liz_kont$V6, ar_2 = liz_kont$V13))

surusiuoti_pavad <- liz_kont_matrica %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "_")
) %>% data.frame

kont_sumos <- cbind(liz_kont, surusiuoti_pavad) %>% 
  rename(kontakto_tipas = ".") %>% 
  group_by(kontakto_tipas) %>% 
  summarise(kontakto_suma = sum(V15)) 

kont_sumos_plat <- spread(kont_sumos, kontakto_tipas, kontakto_suma)

sujungta <- full_join(nul_lentele_plat, kont_sumos_plat) %>% 
  gather() %>% 
  group_by(key) %>% 
  summarise(kontakto_suma = sum(value)) %>% 
  mutate_all(~replace(., is.na(.), 0)) %>% 
  spread(., key, kontakto_suma)

return(sujungta)
}
```

## Bandymas 

Duomenu ikelimas:
```{r}
lizocimo_kontaktai <- data.table::fread("./lizocimai/1L63.contacts.interresidue.table")
nuline_lentele_platusis <- readr::read_rds("./data/nuline_lentele_platusis.rds")
```

```{r}
paruosta_lentele <- fun_kontaktu_sumai(lizocimo_kontaktai, nuline_lentele_platusis)

paruosta_lentele
```

