---
title: "bendras skaiciavimas"
author: "Ema Malinauskaite"
date: "5/6/2020"
output: html_document
---

Idejos ka deti i baki:
```{r}
##skaiciuoja kiek distinct values yra kiekviename kontaktu sumu stulpelyje, ty, kiek baltymu turi ta kontakta/-us, galima pabraizyti grafikeli, veikia paleidus visa koda zemiau
# A_skaiciavimai <- A_df %>% 
#   summarise_all(n_distinct)
```


```{r include=FALSE}
library("tidyverse")
library("data.table")
library("compareDF")
library("tidyr")
library("matlib")
library("pracma")
library("readr")
library("caret")
library(modelr)
set.seed(6)
```

## fun_atomu_grupiu_sumoms

```{r}
fun_atomu_grupiu_sumoms <- function(liz_kont, grupavimo_lentele, nuline_lentele_atomu) { #pirmas kintamasis- kontaktu failas su pridetais pavadinimais ar1_atom1
  
#-------
# Atomu pervadinimas pilnesniu pavadinimu
  
  kontaktai_atomu_pavadinimai <- liz_kont %>%
  select(V6, V7, V13, V14, V15) %>% 
#  filter(V13 != "solvent") %>% 
  mutate(V7 = recode_factor(V7,"OXT" = "O")) %>% 
  mutate(V14 = recode_factor(V14,"OXT" = "O")) %>% 
  mutate(V6 = recode_factor(V6,"MSE" = "MET")) %>% 
  mutate(V13 = recode_factor(V13,"MSE" = "MET"))
  
kontaktai_atomu_pavadinimai$ar1_atom1 <- with(kontaktai_atomu_pavadinimai, paste0(V6,V7))
kontaktai_atomu_pavadinimai$ar2_atom2 <- with(kontaktai_atomu_pavadinimai, paste0(V13,V14))

#------
# Grupes priskyrimas kiekvienam atomui

kontaktai_atomu_pavadinimai <- kontaktai_atomu_pavadinimai %>%
  mutate(grupe1 = 0) %>% 
  mutate(grupe2 = 0)

grupes_pavadinimai <- rownames(grupavimo_lentele) 

for (i in grupes_pavadinimai) {
  viena_eilute <- grupavimo_lentele[i,]
  viena_eilute <- viena_eilute[,colSums(is.na(viena_eilute)) == 0]
    for (j in viena_eilute) { 
        kontaktai_atomu_pavadinimai <- kontaktai_atomu_pavadinimai %>%
        mutate(grupe1 = ifelse(ar1_atom1 == j, i, grupe1)) %>% 
        mutate(grupe2 = ifelse(ar2_atom2 == j, i, grupe2))
    }
}
#-----
# Isrusiuotu pavadinimu grupe1-grupe2 sudarymas ir kontakto sumu skaiciavimas pagal grupes
matrica_pavadinimams <- as.matrix(data.frame(grupe1 = kontaktai_atomu_pavadinimai$grupe1, grupe2 = kontaktai_atomu_pavadinimai$grupe2))

surusiuoti_pavad <- matrica_pavadinimams %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame

atom_kont_sumos <- cbind(kontaktai_atomu_pavadinimai, surusiuoti_pavad) %>% 
  rename(kontakto_tipas = ".") %>% 
  group_by(kontakto_tipas) %>% 
  summarise(kontakto_suma = sum(V15)) 

#-----
# Standartizavimas

atom_kont_sumos <- spread(atom_kont_sumos, kontakto_tipas, kontakto_suma)

sujungta <- full_join(nuline_lentele_atomu, atom_kont_sumos) %>%
  gather() %>%
  group_by(key) %>%
  summarise(kontakto_suma = sum(value)) %>%
  mutate_all(~replace(., is.na(.), 0)) %>%
  spread(., key, kontakto_suma)

#----------
return(sujungta)
}
```

## Fun_matricu_paruosimas_atom

```{r}
fun_matricu_paruosimas_atom <- function(pdb_termo_lent, grupavimo_failas) {
visu_baltymu_kont_sumu_skirtumai <- data.frame() 
termo_skirtumai <- data.frame() #desine tiesiniu lygciu sistemos puse matricose 
#----
#Grupavimo lenteles sukurimas (reiklainga kitai funkcijai)
grupavimo_lentele <- grupavimo_failas %>% 
  mutate_all(na_if,"") %>% 
  tibble::column_to_rownames(var = "V1") %>% 
  rbind(solvent = c("solventsolvent"))

#-------
# Nulines lenteles kurimas (reikalinga kitai funkcijai)
grupes_pavadinimai <- rownames(grupavimo_lentele) 
nuline_lentele_atomu_grupiu_pavadinimai<- data.frame(1:(nrow(grupavimo_lentele)^2))

nuline_lentele_atomu_grupiu_pavadinimai$pirma <- data.frame(rep(grupes_pavadinimai, each = nrow(grupavimo_lentele)))
nuline_lentele_atomu_grupiu_pavadinimai$antra <- rep(grupes_pavadinimai, times = nrow(grupavimo_lentele))

matrica_pavadinimams_nuline <- as.matrix(data.frame(grupe1 = nuline_lentele_atomu_grupiu_pavadinimai$pirma, grupe2 = nuline_lentele_atomu_grupiu_pavadinimai$antra))

nuline_lentele_atomu <- matrica_pavadinimams_nuline %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame() %>% 
  rename("kontakto_tipas" = ".")


nuline_lentele_atomu$nuliai <- rep(0, times = nrow(nuline_lentele_atomu)) 

nuline_lentele_atomu <- nuline_lentele_atomu %>% 
  group_by(kontakto_tipas) %>% 
  summarise(nuliai = sum(nuliai)) %>% 
  transpose(make.names = "kontakto_tipas") %>% 
  select(-"solvent-solvent")

#-------
#wtx ir wt standartiniu lenteliu sukurimas
lizocimo_kontaktai_wt <- data.table::fread("./lizocimai/2LZM.contacts.interatom.table", na.strings = ".")

lizocimo_kontaktai_wt <- lizocimo_kontaktai_wt %>%
  mutate(V13 = recode_factor(V13, .missing = "solvent")) %>%
  mutate(V14 = recode_factor(V14, .missing = "solvent"))

wt_atom <- fun_atomu_grupiu_sumoms(lizocimo_kontaktai_wt, grupavimo_lentele, nuline_lentele_atomu)

lizocimo_kontaktai_wtx <- data.table::fread("./lizocimai/1L63.contacts.interatom.table", na.strings = ".")

lizocimo_kontaktai_wtx <- lizocimo_kontaktai_wtx %>%
  mutate(V13 = recode_factor(V13, .missing = "solvent")) %>%
  mutate(V14 = recode_factor(V14, .missing = "solvent"))

wtx_atom <- fun_atomu_grupiu_sumoms(lizocimo_kontaktai_wtx,  grupavimo_lentele, nuline_lentele_atomu)
#----
for (i in pdb_termo_lent$pdb) {
lizocimo_kontaktai <- data.table::fread(paste("./lizocimai/",i,".contacts.interatom.table", sep = ""), na.strings = ".")

lizocimo_kontaktai <- lizocimo_kontaktai %>%
  mutate(V13 = recode_factor(V13, .missing = "solvent")) %>%
  mutate(V14 = recode_factor(V14, .missing = "solvent"))

kontaktu_sumos_atom <- fun_atomu_grupiu_sumoms(lizocimo_kontaktai,  grupavimo_lentele, nuline_lentele_atomu)

viena_eilute <- pdb_termo_lent %>% 
  filter(pdb == i)
  
if (viena_eilute$WT == "wt") {
  wt_ir_lizocimas_atom <- rbind(wt_atom, kontaktu_sumos_atom) %>%
  transpose(keep.names = "kontakto_tipas") %>% 
  mutate(kont_sumu_skirtumas = V1 - V2) %>% 
  select(kontakto_tipas, kont_sumu_skirtumas) %>% 
  transpose(make.names = "kontakto_tipas")
} else {
  wt_ir_lizocimas_atom <- rbind(wtx_atom, kontaktu_sumos_atom) %>%
  transpose(keep.names = "kontakto_tipas") %>% 
  mutate(kont_sumu_skirtumas = V1 - V2) %>% 
  select(kontakto_tipas, kont_sumu_skirtumas) %>% 
  transpose(make.names = "kontakto_tipas")
}

visu_baltymu_kont_sumu_skirtumai <- rbind(visu_baltymu_kont_sumu_skirtumai, wt_ir_lizocimas_atom)
lizocimo_kontaktai = NULL
 }
termo_skirtumai <- pdb_termo_lent %>%
  select(-WT, -pdb)

return(list(visu_baltymu_kont_sumu_skirtumai_atom = as.matrix(visu_baltymu_kont_sumu_skirtumai),termo_skirtumai_atom = as.matrix(termo_skirtumai)))
}

```



## Duomenu ikelimas
```{r}

lizocimai_pagr <- readr::read_rds("./data/pro_344_sm_suppinfo.rds")
lizocimai_pagr_su_mutacijom <- readr::read_rds("./data/lizocimai_pagr_su_mutacijom.rds")

pdb_tm_wt_mut <- lizocimai_pagr_su_mutacijom %>% 
  select(pdb, deltaTm, WT, mut_skaicius) %>% 
  filter(pdb != "2LZM" & pdb != "1L63" & pdb != "219L" ) %>% 
  .[-(105:121),] %>% 
  filter(mut_skaicius < 3) %>% 
  select(-mut_skaicius) %>% 
  filter(deltaTm > -25)
  
# Sukuriama tokia pati pdb_tm_wt_mut lnetele kaip skaiciavimui, tik su visais stulpeliais
pdb_tm_wt_mut_visi_stulpeliai <- lizocimai_pagr_su_mutacijom %>% 
  filter(pdb != "2LZM" & pdb != "1L63" & pdb != "219L" ) %>% 
  .[-(105:121),] %>% 
  filter(mut_skaicius < 3) %>% 
  filter(deltaTm > -25)

pdb_tm_wt_mut_visi_stulpeliai
```

## Skaiciavimai
```{r, message=FALSE}
# Atomu tipu nuskaitymas cikle
for(e in c("RESIDUE")) { 
atom_types_parsiuntimui <- e
 grupavimo_failas <- data.table::fread(paste0("/Users/user/Desktop/praktika/r-praktika/atom_types/",atom_types_parsiuntimui, ".atoms"), 
  dec = ".", header = FALSE, skip = 1, encoding = "UTF-8", fill = TRUE,
  data.table = FALSE
)
 
atom_types <- paste0(e, "_mut2_beHISLYS_PROPRO_TRPTRP") # Pavadinimo dalis, kuri nusako koks atomu grupavimo tipas, bei kita info
#---- 
# Reiklaingu matricu sukurimas
matricu_lenteles <- fun_matricu_paruosimas_atom(pdb_termo_lent = pdb_tm_wt_mut, grupavimo_failas = grupavimo_failas)

A <- matricu_lenteles$visu_baltymu_kont_sumu_skirtumai_atom %>%  .[,-c(144, 204, 225)]
b <- c(matricu_lenteles$termo_skirtumai_atom)
duomenys_cv <- data.frame(b, A) 

#----------
# TLS be CV 

tls_sprendimas_visi_baltymai <- 
  pracma::qrSolve(A, b)

apsk_temp_is_visu <- 
  A %*% tls_sprendimas_visi_baltymai

apsk_ir_teor_temp_is_visu <- cbind(pdb_tm_wt_mut_visi_stulpeliai, data.frame(apsk_temp_is_visu)) 

apsk_ir_teor_temp_is_visu

saveRDS(apsk_ir_teor_temp_is_visu, file = 
  paste0("rds-failai/apsk_ir_teor_temp_is_visu-",atom_types,".rds"))

#------
r2_is_visu <- apsk_ir_teor_temp_is_visu %>% 
  mutate(r2 = (deltaTm - apsk_temp_is_visu)^2) %>% 
  summarise(r2 = round(sum(r2), 2))

# LOOCV
#------
eil_skaicius <- nrow(duomenys_cv)
apsk_temp_loo_cv <- data.frame()

for (i in 1:eil_skaicius) {
print(i)
#Duomenys suskirstomi i train ir test
train_loo <- duomenys_cv[-i,]
test_loo <- duomenys_cv[i,]

#Atskiriamas train temperaturos stulpelis nuo kontaktu plotu stulpeliu
train_loo_teor_temp <- train_loo[,1]
train_loo_kontaktai <- train_loo[,-1]

#Apskaiciuojami koeficientai
koef_loo <- pracma::qrSolve(as.matrix(train_loo_kontaktai), as.matrix(train_loo_teor_temp))

#5
#Atskiriamas test temperaturos stulpelis nuo kontaktu plotu stulpeliu
test_loo_teor_temp <- test_loo[,1]
test_loo_kontaktai <- test_loo[,-1]

#Apskaiciuojamos temperaturos (test_kontaktaiXkoef)
apsk_temp_loo_eil <- as.matrix(test_loo_kontaktai) %*% koef_loo

#Sudaroma teoriniu ir apskaiciuotu temperaturu lentele
apsk_temp_loo_cv <- rbind(apsk_temp_loo_cv, data.frame(apsk_temp_loo_eil))
}

apsk_ir_teor_temp_loo_cv <- data.frame(cbind(pdb_tm_wt_mut_visi_stulpeliai, apsk_temp_loo_cv)) %>% 
  rename("apsk_temp_loo" = "apsk_temp_loo_eil")

saveRDS(apsk_ir_teor_temp_loo_cv, file = 
  paste0("rds-failai/apsk_ir_teor_temp_loo_cv-",atom_types,".rds"))

r2_cv_loo <- apsk_ir_teor_temp_loo_cv %>% 
  mutate(r2 = (deltaTm - apsk_temp_loo)^2) %>% 
  summarise(r2 = round(sum(r2), 2))

# Visi grafikai:

be_cv_grafikas <- ggplot(apsk_ir_teor_temp_is_visu) +
aes(x = deltaTm, y = apsk_temp_is_visu, color = pH_grupe) +
    labs(x = "Teorinis temperaturu skirtumas",
         y = "Apskaiciuotas temperaturu skirtumas",
         title = paste0("Be CV (", atom_types, ")"),
         subtitle = paste0("r2 = ",r2_is_visu))+
 geom_point(size = 1L) +
 theme_minimal() +
 facet_wrap(~WT)

cv_loo_grafikas <- ggplot(apsk_ir_teor_temp_loo_cv) +
 aes(x = deltaTm, y = apsk_temp_loo, color = pH_grupe) +
    labs(x = "Teorinis temperaturu skirtumas",
         y = "Apskaiciuotas temperaturu skirtumas",
         title = paste0("LOOCV (", atom_types, ")"),
         subtitle = paste0("r2 = ", r2_cv_loo)
         ) +
 geom_point(size = 1L) +
 theme_minimal() +
 facet_wrap(~WT)

cv_loo_grafikas_filtered <- ggplot(apsk_ir_teor_temp_loo_cv %>% filter(apsk_temp_loo > (-100) & apsk_temp_loo < 100)) +
 aes(x = deltaTm, y = apsk_temp_loo, color = pH_grupe) +
    labs(x = "Teorinis temperaturu skirtumas",
         y = "Apskaiciuotas temperaturu skirtumas",
         title = paste0("LOOCV (", atom_types, ")"),
         subtitle = paste0("r2 = ", r2_cv_loo)) +
 geom_point(size = 1L) +
 theme_minimal() +
 facet_wrap(~WT)

# ggsave(be_cv_grafikas, device = "jpeg",filename = paste0(atom_types, "_be_cv.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")

# ggsave(cv_loo_grafikas, device = "jpeg",filename = paste0(atom_types, "_loo_cv.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")
# 
# ggsave(cv_loo_grafikas_filtered, device = "jpeg",filename = paste0(atom_types, "_loo_cv_filtered.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")

be_cv_grafikas
cv_loo_grafikas
cv_loo_grafikas_filtered
}
```






## Skaiciavimas naudojant absoliucias reiksmes

Funkcijos absoliuciom reiksmem gauti kurimas:
```{r}
fun_matricu_paruosimas_absoliuciom_reiksmem <- function(pdb_termo_lent, grupavimo_failas) {
visu_baltymu_kont_sumos_absoliucios <- data.frame() 
termo_skirtumai <- data.frame() #desine tiesiniu lygciu sistemos puse matricose 
#----
#Grupavimo lenteles sukurimas (reiklainga kitai funkcijai)
grupavimo_lentele <- grupavimo_failas %>% 
  mutate_all(na_if,"") %>% 
  tibble::column_to_rownames(var = "V1") %>% 
  rbind(solvent = c("solventsolvent"))

#-------
# Nulines lenteles kurimas (reikalinga kitai funkcijai)
grupes_pavadinimai <- rownames(grupavimo_lentele) 
nuline_lentele_atomu_grupiu_pavadinimai<- data.frame(1:(nrow(grupavimo_lentele)^2))

nuline_lentele_atomu_grupiu_pavadinimai$pirma <- data.frame(rep(grupes_pavadinimai, each = nrow(grupavimo_lentele)))
nuline_lentele_atomu_grupiu_pavadinimai$antra <- rep(grupes_pavadinimai, times = nrow(grupavimo_lentele))

matrica_pavadinimams_nuline <- as.matrix(data.frame(grupe1 = nuline_lentele_atomu_grupiu_pavadinimai$pirma, grupe2 = nuline_lentele_atomu_grupiu_pavadinimai$antra))

nuline_lentele_atomu <- matrica_pavadinimams_nuline %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame() %>% 
  rename("kontakto_tipas" = ".")


nuline_lentele_atomu$nuliai <- rep(0, times = nrow(nuline_lentele_atomu)) 

nuline_lentele_atomu <- nuline_lentele_atomu %>% 
  group_by(kontakto_tipas) %>% 
  summarise(nuliai = sum(nuliai)) %>% 
  transpose(make.names = "kontakto_tipas") %>% 
  select(-"solvent-solvent")

#----
for (i in pdb_termo_lent$pdb) {
lizocimo_kontaktai <- data.table::fread(paste("./lizocimai/",i,".contacts.interatom.table", sep = ""), na.strings = ".")

lizocimo_kontaktai <- lizocimo_kontaktai %>%
  mutate(V13 = recode_factor(V13, .missing = "solvent")) %>%
  mutate(V14 = recode_factor(V14, .missing = "solvent"))

kontaktu_sumos_atom <- fun_atomu_grupiu_sumoms(lizocimo_kontaktai,  grupavimo_lentele, nuline_lentele_atomu)

print(i)



visu_baltymu_kont_sumos_absoliucios <- rbind(visu_baltymu_kont_sumos_absoliucios, kontaktu_sumos_atom)
lizocimo_kontaktai = NULL
 }
termo_skirtumai <- pdb_termo_lent %>%
  select(-WT, -pdb)

return(list(visu_baltymu_kont_sumos_absoliucios = as.matrix(visu_baltymu_kont_sumos_absoliucios),termo_skirtumai_atom = as.matrix(termo_skirtumai)))
}

```

Skaiciavimai: (TLS ir LOOCV)
```{r, message=FALSE}
# TLS be CV 

tls_sprendimas_visi_baltymai <- pracma::qrSolve(A, b) #A ir b naudojamos is kodo auksciau

absoliucios_kontaktu_reiksmes <- fun_matricu_paruosimas_absoliuciom_reiksmem(pdb_termo_lent = pdb_tm_wt_mut, grupavimo_failas = grupavimo_failas)

apsk_absoliucios_temp_is_visu <- 
  absoliucios_kontaktu_reiksmes$visu_baltymu_kont_sumos_absoliucios[,-c(144, 204, 225)] %*% tls_sprendimas_visi_baltymai

apsk_ir_teor_absoliucios_temp_is_visu <- cbind(pdb_tm_wt_mut_visi_stulpeliai, data.frame(apsk_absoliucios_temp_is_visu)) 

apsk_ir_teor_absoliucios_temp_is_visu

saveRDS(apsk_ir_teor_absoliucios_temp_is_visu, file =
  paste0("rds-failai/apsk_ir_teor_absoliucios_temp_is_visu-",atom_types,".rds"))

# Grafikui
#--------
r2_absoliucios_is_visu <- apsk_ir_teor_absoliucios_temp_is_visu %>%
  mutate(r2 = (Tm - apsk_absoliucios_temp_is_visu)^2) %>%
  summarise(r2 = round(sum(r2), 2))

be_cv_absoliucios_grafikas <- ggplot(apsk_ir_teor_absoliucios_temp_is_visu) +
aes(x = Tm, y = apsk_absoliucios_temp_is_visu, color = WT) +
    labs(x = "Teorines temperaturos",
         y = "Apskaiciuotos temperaturos",
         title = paste0("Be CV, absoliucios (", atom_types, ")"),
         subtitle = paste0("r2 = ",r2_absoliucios_is_visu))+
 geom_point(size = 1L) +
 theme_minimal()

be_cv_absoliucios_grafikas

ggsave(be_cv_absoliucios_grafikas, device = "jpeg",filename = paste0(atom_types, "_be_cv_absoliucios.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")

```

### Tikrinimas
ar-ar pavadinimu sukurimas:
```{r}
#-----
grupavimo_lentele <- grupavimo_failas %>% 
  mutate_all(na_if,"") %>% 
  tibble::column_to_rownames(var = "V1") %>% 
  rbind(solvent = c("solventsolvent"))

grupes_pavadinimai <- rownames(grupavimo_lentele) 

nuline_lentele_atomu_grupiu_pavadinimai<- data.frame(1:(nrow(grupavimo_lentele)^2))

nuline_lentele_atomu_grupiu_pavadinimai$pirma <- data.frame(rep(grupes_pavadinimai, each = nrow(grupavimo_lentele)))
nuline_lentele_atomu_grupiu_pavadinimai$antra <- rep(grupes_pavadinimai, times = nrow(grupavimo_lentele))

matrica_pavadinimams_nuline <- as.matrix(data.frame(grupe1 = nuline_lentele_atomu_grupiu_pavadinimai$pirma, grupe2 = nuline_lentele_atomu_grupiu_pavadinimai$antra))

nuline_lentele_atomu <- matrica_pavadinimams_nuline %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame() %>% 
  rename("kontakto_tipas" = ".")

nuline_lentele_atomu$nuliai <- rep(0, times = nrow(nuline_lentele_atomu)) 

nuline_lentele_atomu <- nuline_lentele_atomu %>% 
  group_by(kontakto_tipas) %>% 
  summarise(nuliai = sum(nuliai)) %>% 
  transpose(make.names = "kontakto_tipas")%>% 
  select(-"solvent-solvent")

pavadinimai <- nuline_lentele_atomu %>%
  transpose(keep.names = "kontakto_tipas") %>% 
  slice(-c(144, 204, 225)) %>% 
  select(-V1)
```

Koeficientai su pavadinimais:
```{r}
koef_su_pavad <- cbind(pavadinimai, data.frame(tls_sprendimas_visi_baltymai)) %>%  arrange(tls_sprendimas_visi_baltymai)
koef_su_pavad
```

Patikrinimas, kurie kontaktai wt ir wtx grupese yra reti:
```{r}
kontaktu_sumos_ir_visa_kita <- cbind(absoliucios_kontaktu_reiksmes$visu_baltymu_kont_sumos_absoliucios[,-c(144, 204, 225)], apsk_ir_teor_absoliucios_temp_is_visu)

#Bendrai ir wt ir wtx
kontaktu_sumos_wt_ir_wtx <- kontaktu_sumos_ir_visa_kita %>% 
  select(c(1:227))

kontaktu_sumos_wt_ir_wtx_susumuotos <- kontaktu_sumos_wt_ir_wtx %>% 
  summarise_all(n_distinct)

kontaktu_sumos_wt_ir_wtx_susumuotos[which(kontaktu_sumos_wt_ir_wtx_susumuotos < 4)] %>% 
  transpose(keep.names = "pavadinimai") %>% 
  rename("wt_ir_wtx" = "V1")

#isskiriamos dvi grupes, pagal kurias susumuojami kontaktai: wt ir wtx
#wt
kontaktu_sumos_tik_wt <- kontaktu_sumos_ir_visa_kita %>% 
  filter(WT == "wt") %>% 
  select(c(1:227))

kontaktu_sumos_tik_wt_susumuotos <- kontaktu_sumos_tik_wt %>% 
  summarise_all(n_distinct)

kontaktu_sumos_tik_wt_susumuotos[which(kontaktu_sumos_tik_wt_susumuotos < 3)] %>% 
  transpose(keep.names = "pavadinimai") %>% 
  rename("wt" = "V1")

#wtx
kontaktu_sumos_tik_wtx <- kontaktu_sumos_ir_visa_kita %>% 
  filter(WT == "wtx") %>% 
  select(c(1:227))

kontaktu_sumos_tik_wtx_susumuotos <- kontaktu_sumos_tik_wtx %>% 
  summarise_all(n_distinct)

kontaktu_sumos_tik_wtx_susumuotos[which(kontaktu_sumos_tik_wtx_susumuotos < 3)] %>% 
  transpose(keep.names = "pavadinimai") %>% 
  rename("wtx" = "V1")


 
```

