---
title: "heatmap-grafikas"
author: "Ema Malinauskaite"
date: "3/9/2020"
output: html_document
---

```{r include=FALSE}
library("tidyverse")
library("data.table")
library("compareDF")
library("tidyr")
#library("matlib")
library("pracma")
#library("Smisc")
library("readr")
```

# Bandymas nubraizyti pagal atomu tankio grafika, kur kontaktas isskirtas i atskiras amino-rugstis

Duomenu ikelimas:
```{r}
lizocimo_kontaktai <- data.table::fread("./lizocimai/1L63.contacts.interresidue.table")
nuline_lentele_platusis <- readr::read_rds("./data/nuline_lentele_platusis.rds")
aminorugstys <-
  readxl::read_excel(
    "/Users/user/Desktop/praktika/papildomi/aminorugstys.xlsx",
    sheet = "Sheet1"
  ) %>%
  as.data.frame(stringsAsFactors = FALSE)
```

aminorugsciu paruosimas
```{r}
surusiuoti_pavad <- aminorugstys %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "_")
) %>% data.frame %>% 
  rename("kontaktas" = ".")

pavadinimai_pavadinimai <- cbind(surusiuoti_pavad, aminorugstys) 
```

## visu baltymu kontaktu plotu sumavimas
```{r, message= FALSE}
lizocimai_pagr <- readr::read_rds("./data/pro_344_sm_suppinfo.rds")
nul_lent_plat <- readr::read_rds("./data/nuline_lentele_platusis.rds")
pavadinimai_230 <- nul_lent_plat %>% 
  transpose(keep.names = "pavadinimai") %>% 
  rename(suma = V1)

pdb_tm_pvz <- lizocimai_pagr %>% 
  filter(pdb != "2LZM" & pdb != "1L63") %>% 
  select(pdb, deltaTm, WT) %>% 
  drop_na(pdb, deltaTm)
```

```{r, message=FALSE}
visos_kontaktu_sumos <- pavadinimai_230
for (i in pdb_tm_pvz$pdb) {
lizocimo_kontaktai <- data.table::fread(paste("./lizocimai/",i,".contacts.interresidue.table", sep = ""))
kontaktu_sumos <- fun_kontaktu_sumai(lizocimo_kontaktai, nul_lent_plat) %>% 
  transpose(keep.names = "pavadinimai") %>% 
  select(-pavadinimai) %>% 
  rename(!!i := V1)

visos_kontaktu_sumos <- cbind(visos_kontaktu_sumos, kontaktu_sumos)
visos_kontaktu_sumos <- visos_kontaktu_sumos %>% 
  mutate(suma = suma + .[[3]]) %>% 
  select(pavadinimai, suma)
}
visos_kontaktu_sumos
```

## Inputo paruosimas:
```{r}
pilna_lentele <- 
  dplyr::full_join(visos_kontaktu_sumos, pavadinimai_pavadinimai,
  by = c("pavadinimai" = "kontaktas") 
) %>% 
  select(-pavadinimai) %>% 
  mutate(suma = round(suma,0)) %>% 
  filter(ar_1 != ".") 

pilna_lentele
```

grafikas:

```{r}
library("ggplot2")

# Heatmap 
ggplot(pilna_lentele, aes(x = ar_1, y= ar_2, fill = suma)) + 
  geom_tile() +
  scale_fill_gradient(low="red", high="blue") +
  geom_text(aes(ar_1, ar_2, label = suma), color = "black", size = 4) 
```
