---
title: "jbdf"
author: "Ema Malinauskaite"
date: "3/12/2020"
output: html_document
---
## hidrofobines ir hidrofilines

Duomenu ikelimas:
```{r}
grupavimo_failas_1 <- data.table::fread(
  "/Users/user/Desktop/praktika/r-praktika/atom types/RJ.atoms",
  dec = ".", header = FALSE, skip = 1, encoding = "UTF-8", fill = TRUE,
  data.table = FALSE
)

lizocimai_pagr <- readr::read_rds("./data/pro_344_sm_suppinfo.rds")
pdb_tm_wt <- lizocimai_pagr %>% 
  select(pdb, deltaTm, WT) %>% 
  drop_na(pdb, deltaTm) %>% 
  filter(pdb != "2LZM" & pdb != "1L63") %>% 
  .[-(105:121),]

pdb_tm_wt
```

Matricu sukurimas:
```{r message=FALSE}
matricu_lenteles <- fun_matricu_paruosimas_atom(pdb_termo_lent = pdb_tm_wt, grupavimo_failas = grupavimo_failas_1)
```

Reiksmiu priskyrimas:
```{r}
A <- matricu_lenteles$visu_baltymu_kont_sumu_skirtumai_atom
b <- c(matricu_lenteles$termo_skirtumai_atom) 
dim(A)
```

Surasti netinkamiems:
```{r}
rankifremoved <- sapply(1:ncol(A), function (x) qr(A[,-x])$rank)
rankifremoved
which(rankifremoved == max(rankifremoved))
```

```{r}
tls_sprendimas_visi_baltymai <- pracma::qrSolve(A, b)
```

### Aprasomoji
Pavadinimu sukurimas:
```{r}
grupavimo_lentele <- grupavimo_failas_1 %>% 
  mutate_all(na_if,"") %>% 
  tibble::column_to_rownames(var = "V1")
grupes_pavadinimai <- rownames(grupavimo_lentele) 

nuline_lentele_atomu_grupiu_pavadinimai<- data.frame(1:(nrow(grupavimo_lentele)^2))

nuline_lentele_atomu_grupiu_pavadinimai$pirma <- data.frame(rep(grupes_pavadinimai, each = nrow(grupavimo_lentele)))
nuline_lentele_atomu_grupiu_pavadinimai$antra <- rep(grupes_pavadinimai, times = nrow(grupavimo_lentele))

matrica_pavadinimams_nuline <- as.matrix(data.frame(grupe1 = nuline_lentele_atomu_grupiu_pavadinimai$pirma, grupe2 = nuline_lentele_atomu_grupiu_pavadinimai$antra))

nuline_lentele_atomu <- matrica_pavadinimams_nuline %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame() %>% 
  rename("kontakto_tipas" = ".")


nuline_lentele_atomu$nuliai <- rep(0, times = nrow(nuline_lentele_atomu)) 

nuline_lentele_atomu <- nuline_lentele_atomu %>% 
  group_by(kontakto_tipas) %>% 
  summarise(nuliai = sum(nuliai)) %>% 
  transpose(make.names = "kontakto_tipas")


pavadinimai <- nuline_lentele_atomu %>%
  transpose(keep.names = "kontakto_tipas") %>% 
  select(-V1)

pavadinimai
```



```{r}
tls_sprendimas_visi_baltymai_df <- cbind(pavadinimai, data.frame(tls_sprendimas_visi_baltymai))
tls_sprendimas_visi_baltymai_df 

# data.table::fwrite(
#   tls_sprendimas_wt_ir_wtx_df,
#   file = "./rezultatai/koef_visi_lizocimai_qr_metodu_be_TRP.txt",
#   sep = "\t",
#   dec = ".",
#   row.names  = FALSE,
#   col.names  = TRUE,
#   na = ""
# )
```

```{r}
tls_sprendimas_visi_baltymai_df %>%  summary()

arrange(tls_sprendimas_visi_baltymai_df, tls_sprendimas_visi_baltymai) 

tls_sprendimas_visi_baltymai_df %>% 
  filter(str_detect(kontakto_tipas, "\\.")) %>% 
  arrange(tls_sprendimas_visi_baltymai)

```

temperaturos skirtumu apskaiciavimas turint koeficientus ir qq grafikas
```{r}
apskaiciuotos_temperaturos <- 
  matricu_lenteles$visu_baltymu_kont_sumu_skirtumai_atom %*% tls_sprendimas_visi_baltymai

apskaiciuotos_ir_teorines_temperaturos_df <- cbind(pdb_tm_wt, data.frame(apskaiciuotos_temperaturos)) %>% 
  select(-WT)

ggplot(apskaiciuotos_ir_teorines_temperaturos_df) +
 aes(x = deltaTm, y = apskaiciuotos_temperaturos) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 theme_minimal()

apskaiciuotos_ir_teorines_temperaturos_df %>% 
  mutate(skirtumas = round((deltaTm- apskaiciuotos_temperaturos), digits = 3)) %>%
  arrange(skirtumas)
  
```

