---
title: "lizocimai-bandymas"
author: "Ema Malinauskaite"
date: "1/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library("tidyverse")
library("data.table")
```

Duomenu ikelimas:
```{r}
lizocimo_kontaktai <- data.table::fread("./lizocimai/102L.pdb1.contacts.iterresue.table")
```

Naudojamu kintamuju pervadinimas:
```{r}
lizocimo_kontaktai <- lizocimo_kontaktai %>%
  rename(
    id_1 = V2,
    ar_1 = V6,
    id_2 = V9,
    ar_2 = V13, 
    plotas = V15
  )
```

Paliekami tik reikalingi stulpeliai ir ismetami kontaktai su vandeniu:
```{r}
lizocimo_kontaktai_be <- lizocimo_kontaktai %>%
  mutate_if(is.character, as_factor) %>% 
  select(id_1, ar_1, id_2, ar_2, plotas) %>% 
  filter(ar_2 != ".")
```

```{r}
head(lizocimo_kontaktai_be) 
```

Kontakto tipas sudaromas taip, kad pirma isrikiuojama eilute, tada sudaromas pavadinimas ir tuomet poras galima skaiciuoti neatsizvelgiant i tvarka:
```{r}
liz_kont_matrica <- as.matrix(data.frame(ar_1 = lizocimo_kontaktai_be$ar_1, ar_2 = lizocimo_kontaktai_be$ar_2))

surusiuoti_pavad <- liz_kont_matrica %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "_")
) %>% data.frame

 head(surusiuoti_pavad)
```

Prijungiamas stulpelis su kontakto tipu prie pagrindines duomenu lenteles:
```{r}
lizocimo_kontaktai_be <- cbind(lizocimo_kontaktai_be, surusiuoti_pavad) %>% 
  rename(kontakto_tipas = ".")

head(lizocimo_kontaktai_be)
```

```{r}
sumos_pagal_kont <- lizocimo_kontaktai_be %>% 
  group_by(kontakto_tipas) %>% 
  summarise(kontakto_suma = sum(plotas)) 

head(sumos_pagal_kont)
```










