---
title: "tls_sprendimas_atom"
author: "Ema Malinauskaite"
date: "3/12/2020"
output: html_document
---

```{r include=FALSE}
library("tidyverse")
library("data.table")
library("compareDF")
library("tidyr")
library("pracma")
library("readr")
```


# TLS sprendimas
## TLS sprendimas visiem grupavimam
-

## ar-ar pagal atomus

Duomenu ikelimas:
```{r}
grupavimo_failas <- data.table::fread(
  "/Users/user/Desktop/praktika/r-praktika/atom types/RESIDUE.atoms",
  dec = ".", header = FALSE, skip = 1, encoding = "UTF-8", fill = TRUE,
  data.table = FALSE
)

lizocimai_pagr <- readr::read_rds("./data/pro_344_sm_suppinfo.rds")
pdb_tm_wt <- lizocimai_pagr %>% 
  select(pdb, deltaTm, WT) %>% 
  drop_na(pdb, deltaTm) %>% 
  filter(pdb != "2LZM" & pdb != "1L63") %>% 
  .[-(105:121),]

pdb_tm_wt
```

Matricu sukurimas:
```{r message=FALSE}
matricu_lenteles <- fun_matricu_paruosimas_atom(pdb_termo_lent = pdb_tm_wt, grupavimo_failas = grupavimo_failas)
```

Reiksmiu priskyrimas:
```{r}
A <- matricu_lenteles$visu_baltymu_kont_sumu_skirtumai_atom[, -205]
b <- c(matricu_lenteles$termo_skirtumai_atom) 
dim(A)
```

Surasti netinkamiems:
```{r}
rankifremoved <- sapply(1:ncol(A), function (x) qr(A[,-x])$rank)
rankifremoved
which(rankifremoved == max(rankifremoved))
```

Sprendimas:
```{r}
tls_sprendimas_visi_baltymai <- pracma::qrSolve(A, b)
```

### Aprasomoji
Pavadinimu sukurimas:
```{r}
grupavimo_lentele <- grupavimo_failas %>% 
  mutate_all(na_if,"") %>% 
  tibble::column_to_rownames(var = "V1")
grupes_pavadinimai <- rownames(grupavimo_lentele) 

nuline_lentele_atomu_grupiu_pavadinimai<- data.frame(1:(nrow(grupavimo_lentele)^2))

nuline_lentele_atomu_grupiu_pavadinimai$pirma <- data.frame(rep(grupes_pavadinimai, each = nrow(grupavimo_lentele)))
nuline_lentele_atomu_grupiu_pavadinimai$antra <- rep(grupes_pavadinimai, times = nrow(grupavimo_lentele))

matrica_pavadinimams_nuline <- as.matrix(data.frame(grupe1 = nuline_lentele_atomu_grupiu_pavadinimai$pirma, grupe2 = nuline_lentele_atomu_grupiu_pavadinimai$antra))

nuline_lentele_atomu <- matrica_pavadinimams_nuline %>% 
  split(., row(.)) %>% sapply(
  . %>% sort %>% paste(collapse = "-")
) %>% data.frame() %>% 
  rename("kontakto_tipas" = ".")


nuline_lentele_atomu$nuliai <- rep(0, times = nrow(nuline_lentele_atomu)) 

nuline_lentele_atomu <- nuline_lentele_atomu %>% 
  group_by(kontakto_tipas) %>% 
  summarise(nuliai = sum(nuliai)) %>% 
  transpose(make.names = "kontakto_tipas")


pavadinimai <- nuline_lentele_atomu %>%
  transpose(keep.names = "kontakto_tipas") %>% 
 # slice(-205) %>% 
  select(-V1)

pavadinimai
```

```{r}
tls_sprendimas_visi_baltymai_df <- cbind(pavadinimai, data.frame(tls_sprendimas_visi_baltymai))
tls_sprendimas_visi_baltymai_df 

# data.table::fwrite(
#   tls_sprendimas_wt_ir_wtx_df,
#   file = "./rezultatai/koef_visi_lizocimai_qr_metodu_be_TRP.txt",
#   sep = "\t",
#   dec = ".",
#   row.names  = FALSE,
#   col.names  = TRUE,
#   na = ""
# )
```


```{r}
tls_sprendimas_visi_baltymai_df %>%  summary()

arrange(tls_sprendimas_visi_baltymai_df, tls_sprendimas_visi_baltymai) 

tls_sprendimas_visi_baltymai_df %>% 
  filter(str_detect(kontakto_tipas, "\\.")) %>% 
  arrange(tls_sprendimas_visi_baltymai)

```

temperaturos skirtumu apskaiciavimas turint koeficientus ir qq grafikas
```{r}
ggplot(tls_sprendimas_visi_baltymai_df) +
 aes(x = tls_sprendimas_visi_baltymai) +
 geom_histogram(bins = 30L, fill = "#0c4c8a") +
 theme_minimal()

tls_sprendimas_visi_baltymai_df %>%  summary()

apskaiciuotos_temperaturos <- 
  matricu_lenteles$visu_baltymu_kont_sumu_skirtumai_atom %*% tls_sprendimas_visi_baltymai# [, -205] %*% tls_sprendimas_visi_baltymai

apskaiciuotos_ir_teorines_temperaturos_df <- cbind(pdb_tm_wt, data.frame(apskaiciuotos_temperaturos)) %>% 
  select(-WT)

ggplot(apskaiciuotos_ir_teorines_temperaturos_df) +
 aes(x = deltaTm, y = apskaiciuotos_temperaturos) +
 geom_point(size = 1L, colour = "#0c4c8a") +
 theme_minimal()

apskaiciuotos_ir_teorines_temperaturos_df %>% 
  mutate(skirtumas = round((deltaTm- apskaiciuotos_temperaturos), digits = 3)) %>%
  arrange(skirtumas)
  
```







## Is kito skripto 5fold CV jeigu reiketu prie galutinio galutinio
```{r}
#------
# 5 fold CV su tls
# flds <- createFolds(rownames(duomenys_cv), k = 5, list = TRUE, returnTrain = FALSE)
# 
# apsk_ir_teor_temp_5_cv <- data.frame()
# for (i in 1:5) {
# 
# #4
# #Duomenys suskirstomi i train (4 foldai) ir test (1 foldas)
# train_5 <- flds[-i] %>% unlist() %>% as.vector()
# test_5 <- flds[i] %>% unlist() %>% as.vector()
# 
# #Atskiriamas train temperaturos stulpelis nuo kontaktu plotu stulpeliu
# train_5_teor_temp <- duomenys_cv[train_5,] %>% .[,1]
# train_5_kontaktai <- duomenys_cv[train_5,] %>% .[,-1]
# 
# #Apskaiciuojami koeficientai
# rankifremoved <- sapply(1:ncol(A), function (x) qr(A[,-x])$rank)
# print(which(rankifremoved == max(rankifremoved)))
# koef_5 <- pracma::qrSolve(as.matrix(train_5_kontaktai), as.matrix(train_5_teor_temp))
# 
# #5
# #Atskiriamas test temperaturos stulpelis nuo kontaktu plotu stulpeliu
# test_5_teor_temp <- duomenys_cv[test_5,] %>% .[,1]
# test_5_kontaktai <- duomenys_cv[test_5,] %>% .[,-1]
# 
# #Apskaiciuojamos temperaturos (test_kontaktaiXkoef)
# apsk_temp_5 <- as.matrix(test_5_kontaktai) %*% koef_5
# 
# #Sudaroma teoriniu ir apskaiciuotu temperaturu lentele
# apsk_ir_teor_temp_5_cv <- data.frame(rbind(apsk_ir_teor_temp_5_cv, cbind(data.frame(apsk_temp_5), test_5_teor_temp)))
# }
# apsk_ir_teor_temp_5_cv
# 
# saveRDS(apsk_ir_teor_temp_5_cv, file =
#   paste0("rds-failai/apsk_ir_teor_temp_5_cv-",atom_types,".rds"))
# 
# r2_cv_<- apsk_ir_teor_temp_cv %>%
#   mutate(r2 = (test_teor_temp - apsk_temp)^2) %>%
#   summarise(r2 = round(sum(r2), 2))
# 
# apsk_ir_teor_temp_cv_filter <- apsk_ir_teor_temp_cv %>%
#   filter(apsk_temp > (-100) & apsk_temp < 100)
# 
# cv_grafikas <- ggplot(apsk_ir_teor_temp_cv) +
#  aes(x = test_teor_temp, y = apsk_temp) +
#     labs(x = "Teorinis temperaturu skirtumas",
#          y = "Apskaiciuotas temperaturu skirtumas",
#          title = paste0("CV (", atom_types, ")"),
#          subtitle = paste0("r2 = ", r2_cv)) +
#  geom_point(size = 1L, colour = "#0c4c8a") +
#  theme_minimal()
# 
# cv_grafikas_filtered <- ggplot(apsk_ir_teor_temp_cv %>%  filter(apsk_temp > (-100) & apsk_temp < 100) ) +
#  aes(x = test_teor_temp, y = apsk_temp) +
#     labs(x = "Teorinis temperaturu skirtumas",
#          y = "Apskaiciuotas temperaturu skirtumas",
#          title = paste0("CV (", atom_types, ")"),
#          subtitle = paste0("r2 = ", r2_cv)) +
#  geom_point(size = 1L, colour = "#0c4c8a") +
#  theme_minimal()
# 
# ggsave(cv_grafikas, device = "jpeg",filename = paste0(atom_types, "_cv.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")
# 
# ggsave(cv_grafikas_filtered, device = "jpeg",filename = paste0(atom_types, "_cv_filtered.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")

```

ir ml:
```{r}
#-------
# ML 5-fold CV
# 
# trainingRowIndex <- sample(1:nrow(duomenys_cv), 0.8*nrow(duomenys_cv))  # row indices for training data
# trainingData <- duomenys_cv[trainingRowIndex, ]  # model training data
# testData  <- duomenys_cv[-trainingRowIndex, ]   # test data
# 
# lmMod <- lm(b ~ ., data=trainingData)  # build the model
# distPred <- predict(lmMod, testData)
# summary(lmMod) 
# 
# actuals_preds <- data.frame(cbind(actuals=testData$b, predicteds=distPred))  # make actuals_predicteds dataframe.
# correlation_accuracy <- cor(actuals_preds) 
# head(actuals_preds)
# 
# saveRDS(actuals_preds, file = 
#   paste0("rds-failai/teori_ir_apsk_temp_lm-", atom_types, ".rds"))
# 
# r2_ml <- actuals_preds %>% 
#   mutate(r2 = (actuals - predicteds)^2) %>% 
#   summarise(r2 = round(sum(r2), 2))
# 
# ml_grafikas <- ggplot(actuals_preds) +
# aes(x = actuals, y = predicteds) +
#     labs(x = "Teorinis temperaturu skirtumas",
#          y = "Apskaiciuotas temperaturu skirtumas",
#          title = paste0("LM (", atom_types, ")"),
#          subtitle = paste0("r2 = ",r2_ml))+
#  geom_point(size = 1L, colour = "#0c4c8a") +
#  theme_minimal()
# 
# ml_grafikas_filtered <- ggplot(actuals_preds %>% filter(predicteds > -100 & predicteds < 100)) +
# aes(x = actuals, y = predicteds) +
#     labs(x = "Teorinis temperaturu skirtumas",
#          y = "Apskaiciuotas temperaturu skirtumas",
#          title = paste0("LM (", atom_types, "), filtered"),
#          subtitle = paste0("r2 = ",r2_ml))+
#  geom_point(size = 1L, colour = "#0c4c8a") +
#  theme_minimal()
# 
# ggsave(ml_grafikas, device = "jpeg",filename = paste0(atom_types, "_ml_lm.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")
# 
# ggsave(ml_grafikas_filtered, device = "jpeg",filename = paste0(atom_types, "_ml_lm_filtered.jpeg") ,path = "/Users/user/Desktop/praktika/r-praktika/grafikai")

```
